spring.application.name=fraud-rule-engine-service

server.port=${SERVER_PORT:8081}

internal.security.service-token=${INTERNAL_SERVICE_AUTH_TOKEN:raul}

fraud.case-service.base-url=${FRAUD_CASE_SERVICE_BASE_URL:http://localhost:8082}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

fraud.threshold=100
fraud.rules.travel-max-speed-kmh=900
fraud.rules.card-testing-window-minutes=15
fraud.rules.card-testing-attempt-threshold=3
fraud.rules.dormant-days=180
fraud.rules.large-amount-multiplier=8
fraud.rules.rapid-activity-tx10-threshold=4
fraud.rules.rapid-activity-tx60-threshold=10
fraud.rules.new-payee-multiplier=5
fraud.rules.salary-drain-window-minutes=60
fraud.rules.salary-drain-transfer-threshold=1000
fraud.rules.low-value-card-limit=10
fraud.rules.high-risk-country-threshold=60

fraud.country-risk-scores.ZA=0
fraud.country-risk-scores.BW=10
fraud.country-risk-scores.NA=10
fraud.country-risk-scores.KE=25
fraud.country-risk-scores.GB=15
fraud.country-risk-scores.US=15
fraud.country-risk-scores.AE=20
fraud.country-risk-scores.NG=80
fraud.country-risk-scores.BR=70
fraud.country-risk-scores.RU=90
fraud.country-risk-scores.LT=75

fraud.geo-locations.ZA.latitude=-25.7479
fraud.geo-locations.ZA.longitude=28.2293
fraud.geo-locations.BW.latitude=-24.6282
fraud.geo-locations.BW.longitude=25.9231
fraud.geo-locations.NA.latitude=-22.5609
fraud.geo-locations.NA.longitude=17.0658
fraud.geo-locations.KE.latitude=-1.2921
fraud.geo-locations.KE.longitude=36.8219
fraud.geo-locations.GB.latitude=51.5072
fraud.geo-locations.GB.longitude=-0.1276
fraud.geo-locations.US.latitude=40.7128
fraud.geo-locations.US.longitude=-74.0060
fraud.geo-locations.AE.latitude=25.2048
fraud.geo-locations.AE.longitude=55.2708
fraud.geo-locations.NG.latitude=6.5244
fraud.geo-locations.NG.longitude=3.3792
fraud.geo-locations.BR.latitude=-23.5505
fraud.geo-locations.BR.longitude=-46.6333
fraud.geo-locations.RU.latitude=55.7558
fraud.geo-locations.RU.longitude=37.6173
fraud.geo-locations.LT.latitude=54.6872
fraud.geo-locations.LT.longitude=25.2797
