spring.application.name=transaction-service

server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_transactions_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

internal.security.service-token=${INTERNAL_SERVICE_AUTH_TOKEN:raul}

fraud.rule-engine.base-url=${FRAUD_RULE_ENGINE_BASE_URL:http://localhost:8081}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

transaction.generator.enabled=true
transaction.generator.schedule-delay-ms=5000
transaction.generator.fraud-percentage=5
