spring.application.name=fraud-case-service

server.port=${SERVER_PORT:8082}

spring.datasource.url=jdbc:postgresql://localhost:5433/fraud_cases_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

internal.security.service-token=${INTERNAL_SERVICE_AUTH_TOKEN:raul}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
