package com.raul.transaction_service.generator;

public enum FraudScenario {
	LARGE_AMOUNT_ABOVE_AVERAGE,
	ODD_HOURS_TRANSACTION,
	KNOWN_FRAUD_ACCOUNT,
	IMPOSSIBLE_TRAVEL,
	NEW_DEVICE_USAGE,
	RAPID_TRANSACTIONS,
	CARD_TESTING,
	NEW_PAYEE_LARGE_TRANSFER,
	SALARY_DRAIN,
	DORMANT_ACCOUNT_ACTIVATED
}
